Repository ISPP-2425/BCC, pull requests merged in 2025-05, with the labels that each got.

#103 docs: update individual feedback from group 5
  docs/grupos-mañana/5-Grupo 5.md
Labels: group 5

#104 docs: update group feedback by group 5
  docs/conocimiento-común/3-MVP.md
  docs/conocimiento-común/4-Análisis de costes y TCO.md
  docs/conocimiento-común/5-Organización del equipo.md
  docs/conocimiento-común/8-Sprint Retrospective.md
  docs/conocimiento-común/9-Demo del producto.md
Labels: group 5, common knowlegde

#107 docs: update individual feedback from group 1
  docs/grupos-mañana/1-Grupo 1.md
Labels: group 1

#106 docs: update individual feedback from group 7
  docs/grupos-tarde/1-Grupo 7.md
Labels: group 7

#108 docs: update group feedback by group 1
  docs/conocimiento-común/0-Presentaciones.md
  docs/conocimiento-común/1-Killer opener.md
Labels: group 1, common knowlegde

#110 docs: update group feedback by group 9 and 10
  docs/conocimiento-común/0-Presentaciones.md
  docs/conocimiento-común/1-Killer opener.md
  docs/conocimiento-común/10-Usuarios piloto.md
  docs/conocimiento-común/11-Desarrollo del producto.md
  docs/conocimiento-común/12-Análisis y garantía de la calidad.md
  docs/conocimiento-común/13-Storyboards y anuncios.md
  docs/conocimiento-común/2-Idea de negocio.md
  docs/conocimiento-común/6-Commitment Agreement.md
  docs/conocimiento-común/7-Uso de la IA.md
  docs/conocimiento-común/9-Demo del producto.md
Labels: group 9, group 10, common knowlegde

#109 docs: update individual feedback from group 10
  docs/grupos-tarde/4-Grupo 10.md
Labels: group 10

#111 docs: update individual feedback from group 3
  docs/grupos-mañana/3-Grupo 3.md
Labels: group 3

#112 docs: update individual feedback from group 4
  docs/grupos-mañana/4-Grupo 4.md
Labels: group 4
